-- ================================================
-- Salma Behery — Products Import
-- Run parts 1→4 in Neon SQL Editor in order
-- ================================================
-- PART 5: Products 241–278 of 278
BEGIN;
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Stainless Steel Crystal Ring','Stainless Steel Crystal Ring','Stainless steel',150.0,NULL,'https://assets.wuiltstore.com/cmmdcqvqx0f2001df662caqxl_mx0hnb1o53z5np5h8vapva522wga.webp','{"https://assets.wuiltstore.com/cmmdcqvqx0f2001df662caqxl_mx0hnb1o53z5np5h8vapva522wga.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Stainless Steel Flowers Bracelet','Stainless Steel Flowers Bracelet','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',280.0,NULL,'https://assets.wuiltstore.com/cmmdcpt330f1a01dfhoyp5pd2_fqxxulsddrv1ugd94r2zsfzk1d55.webp','{"https://assets.wuiltstore.com/cmmdcpt330f1a01dfhoyp5pd2_fqxxulsddrv1ugd94r2zsfzk1d55.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Stainless Steel Hand Chain','Stainless Steel Hand Chain','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',420.0,NULL,'https://assets.wuiltstore.com/cmmdchm3r0eve01df1ypd10hh_kgn1jf5kiepy18hvxr6nq1aw3lhf.webp','{"https://assets.wuiltstore.com/cmmdchm3r0eve01df1ypd10hh_kgn1jf5kiepy18hvxr6nq1aw3lhf.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='hand-chains' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Stainless Steel Hand Chain  Silver','Stainless Steel Hand Chain  Silver','Stainless steel',250.0,NULL,'https://assets.wuiltstore.com/cmmdcreji0f2c01dfd0j1by3u_b3weceutd558hiib7e4byryv4tam.webp','{"https://assets.wuiltstore.com/cmmdcreji0f2c01dfd0j1by3u_b3weceutd558hiib7e4byryv4tam.webp"}',6,true,false,(SELECT id FROM categories WHERE slug='hand-chains' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Stainless Steel Hand Chain 2 Lines With 4 Crystals','Stainless Steel Hand Chain 2 Lines With 4 Crystals','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',350.0,NULL,'https://assets.wuiltstore.com/cmmdcnkbx0ezr01df6mr4b8w5_37b8kple9oqombofpp3qop4oy2m3.webp','{"https://assets.wuiltstore.com/cmmdcnkbx0ezr01df6mr4b8w5_37b8kple9oqombofpp3qop4oy2m3.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='hand-chains' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Stainless Steel Necklace With Brown Rock','Stainless Steel Necklace With Brown Rock','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',200.0,NULL,'https://assets.wuiltstore.com/cmmdch2k10ev201dfbstx4ec5_nmanxsunyg4wj16yq019390nhs9j.webp','{"https://assets.wuiltstore.com/cmmdch2k10ev201dfbstx4ec5_nmanxsunyg4wj16yq019390nhs9j.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='necklace' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Stainless Steel Openwork Band Ring','Stainless Steel Openwork Band Ring','Stainless steel',150.0,NULL,'https://assets.wuiltstore.com/cmmdch5jy0ev401dfe44286on_bbbeojqwan0pnvnhb7tcow9dqb8y.webp','{"https://assets.wuiltstore.com/cmmdch5jy0ev401dfe44286on_bbbeojqwan0pnvnhb7tcow9dqb8y.webp"}',1,true,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Stainless Steel Ring','Stainless Steel Ring','Stainless steel',150.0,NULL,'https://assets.wuiltstore.com/cmmdcj9x50ewo01df7mnphpoz_11on31rx4v6jw6jh228yntqii1gx.webp','{"https://assets.wuiltstore.com/cmmdcj9x50ewo01df7mnphpoz_11on31rx4v6jw6jh228yntqii1gx.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Starburst Signet Stainless Gold Ring','Starburst Signet Stainless Gold Ring','Stainless steel',150.0,NULL,'https://assets.wuiltstore.com/cmmdcs5sx0f2x01df9ukhhcx2_qs56et44xwyfsh073klijw2n827d.webp','{"https://assets.wuiltstore.com/cmmdcs5sx0f2x01df9ukhhcx2_qs56et44xwyfsh073klijw2n827d.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Sun Ring','Sun Ring','stainless steel. free size .',180.0,NULL,'https://assets.wuiltstore.com/cmmdcgjq50euq01dfay546k3c_lu9cfc8h64ev4yzg5j1g7bfgaiqx.webp','{"https://assets.wuiltstore.com/cmmdcgjq50euq01dfay546k3c_lu9cfc8h64ev4yzg5j1g7bfgaiqx.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Sunflower Stainless Steel Ring','Sunflower Stainless Steel Ring','Stainless steel',160.0,NULL,'https://assets.wuiltstore.com/cmmdcm6r80eyt01df9n08duh3_v72ddhyclz8obhpzdb9r9ox7xvsf.webp','{"https://assets.wuiltstore.com/cmmdcm6r80eyt01df9n08duh3_v72ddhyclz8obhpzdb9r9ox7xvsf.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Sunflower With Stainless Steel Bracelet','Sunflower With Stainless Steel Bracelet','Stainless steel',300.0,NULL,'https://assets.wuiltstore.com/cmmdcejcd0eti01df5yjc20y8_ctxxe7p2begm1xo7y9ws6n9xlns2.webp','{"https://assets.wuiltstore.com/cmmdcejcd0eti01df5yjc20y8_ctxxe7p2begm1xo7y9ws6n9xlns2.webp"}',2,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Sunflowers With Green Leaves Bracelet','Sunflowers With Green Leaves Bracelet','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',200.0,NULL,'https://assets.wuiltstore.com/cmmdcox1i0f0n01df9ywiabjf_6o52qmty0qqlp8gwz3rb0whffwog.webp','{"https://assets.wuiltstore.com/cmmdcox1i0f0n01df9ywiabjf_6o52qmty0qqlp8gwz3rb0whffwog.webp"}',7,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Sunflowers With Pink Flowers Bracelet','Sunflowers With Pink Flowers Bracelet','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',220.0,NULL,'https://assets.wuiltstore.com/cmmdcfixv0eu601dfew312xku_nj5xs736bkaj1fm4dyhld8dct674.webp','{"https://assets.wuiltstore.com/cmmdcfixv0eu601dfew312xku_nj5xs736bkaj1fm4dyhld8dct674.webp"}',2,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Traditional Design Stainless Steel Ring','Traditional Design Stainless Steel Ring','Stainless steel',150.0,NULL,'https://assets.wuiltstore.com/cmmdci7yv0evw01dffyl16nsl_ze2fx3cwhelcydc86mq59n82s259.webp','{"https://assets.wuiltstore.com/cmmdci7yv0evw01dffyl16nsl_ze2fx3cwhelcydc86mq59n82s259.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Triple Band Pearl Stainless Steel Ring','Triple Band Pearl Stainless Steel Ring','Stainless steel',150.0,NULL,'https://assets.wuiltstore.com/cmmdclhg20ey501dfe0e83vg7_oqwz043c2u0dhqvuphtnacpraerf.webp','{"https://assets.wuiltstore.com/cmmdclhg20ey501dfe0e83vg7_oqwz043c2u0dhqvuphtnacpraerf.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Triple Star Stainless Steel Ring','Triple Star Stainless Steel Ring','Stainless steel',185.0,NULL,'https://assets.wuiltstore.com/cmmdcp4qm0f0u01dfatfw973l_e8xrpvfrkm10hu3wvkesdlprtr5w.webp','{"https://assets.wuiltstore.com/cmmdcp4qm0f0u01dfatfw973l_e8xrpvfrkm10hu3wvkesdlprtr5w.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Tulip Flowers Bracelet','Tulip Flowers Bracelet','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',280.0,NULL,'https://assets.wuiltstore.com/cmmdcsyz70f3j01dfha1y1ny1_4vg5uaakr5ejstwxb3bwitlkg9dx.webp','{"https://assets.wuiltstore.com/cmmdcsyz70f3j01dfha1y1ny1_4vg5uaakr5ejstwxb3bwitlkg9dx.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Twin Pearl Stainless Steel Ring','Twin Pearl Stainless Steel Ring','Stainless steel',140.0,NULL,'https://assets.wuiltstore.com/cmmdclrgz0eyd01df0rzaeqk7_a2kf4s5mm9aumdi19i294rebw6fw.webp','{"https://assets.wuiltstore.com/cmmdclrgz0eyd01df0rzaeqk7_a2kf4s5mm9aumdi19i294rebw6fw.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Vintage Design Stainless Steel Ring','Vintage Design Stainless Steel Ring','Stainless steel',150.0,NULL,'https://assets.wuiltstore.com/cmmdcx8g30f6901dfbsmj7wac_qe8xuxfat6hoxtpucay3v6pwo7nd.webp','{"https://assets.wuiltstore.com/cmmdcx8g30f6901dfbsmj7wac_qe8xuxfat6hoxtpucay3v6pwo7nd.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Vintage Floral Band Ring','Vintage Floral Band Ring','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',185.0,NULL,'https://assets.wuiltstore.com/cmmdcgmz20eus01df0rgu94iu_yvtbzfzuwbqf23b3xyq3cyxj6ih2.webp','{"https://assets.wuiltstore.com/cmmdcgmz20eus01df0rgu94iu_yvtbzfzuwbqf23b3xyq3cyxj6ih2.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Vintage Multi Stone Band','Vintage Multi Stone Band','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',185.0,NULL,'https://assets.wuiltstore.com/cmmdcpdrw0f1001dfed7k52p3_as2htywxm3wwrjiagdae8flagn9s.webp','{"https://assets.wuiltstore.com/cmmdcpdrw0f1001dfed7k52p3_as2htywxm3wwrjiagdae8flagn9s.webp"}',0,false,false,NULL,NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('White  Baby Blue And Blue Shades Flowers','White  Baby Blue And Blue Shades Flowers','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',200.0,NULL,'https://assets.wuiltstore.com/cmmdcipxp0ew801dfcdxpdffo_aj4pi3povda122lfh55quepkshn7.webp','{"https://assets.wuiltstore.com/cmmdcipxp0ew801dfcdxpdffo_aj4pi3povda122lfh55quepkshn7.webp"}',2,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('White Flower Stainless Steel Ring','White Flower Stainless Steel Ring','Stainless steel . free size.',140.0,NULL,'https://assets.wuiltstore.com/cmmdcngu60ezp01df2sqjavh5_7mmcwlogmk4c927csoo8r7kxgzsy.webp','{"https://assets.wuiltstore.com/cmmdcngu60ezp01df2sqjavh5_7mmcwlogmk4c927csoo8r7kxgzsy.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='rings' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('White Flowers Handmade Necklace','White Flowers Handmade Necklace','Premium jewelry piece.',450.0,NULL,'https://assets.wuiltstore.com/cmmdckrcu0exp01dfdlhbb4u4_mm9r0pg7stg2zsrcl9dhaj5n2oak.webp','{"https://assets.wuiltstore.com/cmmdckrcu0exp01dfdlhbb4u4_mm9r0pg7stg2zsrcl9dhaj5n2oak.webp"}',4,false,false,(SELECT id FROM categories WHERE slug='necklace' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('White Flowers With Gold Bracelet','White Flowers With Gold Bracelet','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',200.0,NULL,'https://assets.wuiltstore.com/cmmdcex2f0ets01df29llbuo1_p9v7ya1d8k9per7xhigpyhthcm7m.webp','{"https://assets.wuiltstore.com/cmmdcex2f0ets01df29llbuo1_p9v7ya1d8k9per7xhigpyhthcm7m.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('White Flowers With Nude Crystals','White Flowers With Nude Crystals','Premium jewelry piece.',200.0,NULL,'https://assets.wuiltstore.com/cmmdcievt0ew001dfexcx561j_iox0xzm4nwvf62wizxxwjxfktbw4.webp','{"https://assets.wuiltstore.com/cmmdcievt0ew001dfexcx561j_iox0xzm4nwvf62wizxxwjxfktbw4.webp"}',2,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('White Flowers With Sunflowers And Garden Bracelet','White Flowers With Sunflowers And Garden Bracelet','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',220.0,NULL,'https://assets.wuiltstore.com/cmmdcfm9u0eu801df8hb84nl0_vxqd2vkxf29605lgad23rtxag2ad.webp','{"https://assets.wuiltstore.com/cmmdcfm9u0eu801df8hb84nl0_vxqd2vkxf29605lgad23rtxag2ad.webp"}',2,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Y Drop Colorful Stones Stainless Steel Necklace','Y Drop Colorful Stones Stainless Steel Necklace','Stainless steel',300.0,NULL,'https://assets.wuiltstore.com/cmmdcqj6a0f1s01dfawiafwrf_do1zqqhh3a6lo3k3smxquzw2fjkf.webp','{"https://assets.wuiltstore.com/cmmdcqj6a0f1s01dfawiafwrf_do1zqqhh3a6lo3k3smxquzw2fjkf.webp"}',1,false,false,(SELECT id FROM categories WHERE slug='necklace' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Zig Zag Blue Light Blue And With Shades','Zig Zag Blue Light Blue And With Shades','Premium jewelry piece.',450.0,NULL,'https://assets.wuiltstore.com/cmmdckn4m0exn01dfcp5mgqb9_5t8oqfwk8u1isadfrv8qqcan3vez.webp','{"https://assets.wuiltstore.com/cmmdckn4m0exn01dfcp5mgqb9_5t8oqfwk8u1isadfrv8qqcan3vez.webp"}',5,false,false,(SELECT id FROM categories WHERE slug='necklace' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Zig Zag Crystal Flowers Coral Shades And White','Zig Zag Crystal Flowers Coral Shades And White','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',240.0,NULL,'https://assets.wuiltstore.com/cmmdck9fb0exf01df0x7ybr1u_3kou83e982uop80yksaxzfnq1snu.webp','{"https://assets.wuiltstore.com/cmmdck9fb0exf01df0x7ybr1u_3kou83e982uop80yksaxzfnq1snu.webp"}',5,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Zigzag  Flowers  Handmade Necklace','Zigzag  Flowers  Handmade Necklace','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',450.0,NULL,'https://assets.wuiltstore.com/cmmdcqp9c0f1w01dfbuid3ktf_kw1t665v40uc2slbtlzkrncncogv.webp','{"https://assets.wuiltstore.com/cmmdcqp9c0f1w01dfbuid3ktf_kw1t665v40uc2slbtlzkrncncogv.webp"}',5,false,false,(SELECT id FROM categories WHERE slug='necklace' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Zigzag Colorful Flowers  Handmade Necklace','Zigzag Colorful Flowers  Handmade Necklace','Premium jewelry piece.',450.0,NULL,'https://assets.wuiltstore.com/cmmdckve70exr01dfem3wakzp_vk2szueqvlfgs7kwp07jsno613d2.webp','{"https://assets.wuiltstore.com/cmmdckve70exr01dfem3wakzp_vk2szueqvlfgs7kwp07jsno613d2.webp"}',4,false,false,(SELECT id FROM categories WHERE slug='necklace' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Zigzag Crystals  Beads Flowers','Zigzag Crystals  Beads Flowers','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',240.0,NULL,'https://assets.wuiltstore.com/cmmdcfxf60eue01dfdfhy3cp0_uxod6nsip4b0reyyzd1u04oubpx8.webp','{"https://assets.wuiltstore.com/cmmdcfxf60eue01dfdfhy3cp0_uxod6nsip4b0reyyzd1u04oubpx8.webp"}',2,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Zigzag Red And White Flowers With Garden Bracelet','Zigzag Red And White Flowers With Garden Bracelet','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',240.0,NULL,'https://assets.wuiltstore.com/cmmdcf65v0etw01df2tiwblly_b00ghfizijq4wg3j24jbjp2sc9jv.webp','{"https://assets.wuiltstore.com/cmmdcf65v0etw01df2tiwblly_b00ghfizijq4wg3j24jbjp2sc9jv.webp"}',2,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('Zigzag White And Black Flowers Bracelet','Zigzag White And Black Flowers Bracelet','will not affected by using water or perfumes . The material is : stainless steel and beads . ï»¿ The length of the bracelet : 16 cm + 5 cm extension.',220.0,NULL,'https://assets.wuiltstore.com/cmmdcfd7o0eu001dfemur2wca_zrieecnw5pljcc2ecvqofv1qjqpv.webp','{"https://assets.wuiltstore.com/cmmdcfd7o0eu001dfemur2wca_zrieecnw5pljcc2ecvqofv1qjqpv.webp"}',2,false,false,(SELECT id FROM categories WHERE slug='bracelet' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('سلسله نجمه البحر ⭐️','سلسله نجمه البحر ⭐️','استانلس ستيل . طول السلسله ٤٠ سم + ٥ سم تطويله .',190.0,NULL,'https://assets.wuiltstore.com/cmmdcjsk90ex301dfdirydgv3_j454bdx11hdlwg0vligpiem5qll8.webp','{"https://assets.wuiltstore.com/cmmdcjsk90ex301dfdirydgv3_j454bdx11hdlwg0vligpiem5qll8.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='necklace' LIMIT 1),NOW(),NOW());
INSERT INTO products (name_en,name_ar,description_en,price,old_price,main_image,images,stock,is_active,is_featured,category_id,created_at,updated_at) VALUES ('قلادة القرون الذهبية الأنيقة','قلادة القرون الذهبية الأنيقة','مصنوعه من الاستانلس ستيل ومطليه بالذهب . طول السلسله ٤٠ سم + ٥ سم تطويله .',250.0,NULL,'https://assets.wuiltstore.com/cmmdcjpng0ex101dfgbphayp5_k3f7e00zstg78qz63bo7n452es3o.webp','{"https://assets.wuiltstore.com/cmmdcjpng0ex101dfgbphayp5_k3f7e00zstg78qz63bo7n452es3o.webp"}',0,false,false,(SELECT id FROM categories WHERE slug='necklace' LIMIT 1),NOW(),NOW());
COMMIT;
